window.SENTENCES_AUDIO_MAP = {
  "Letter Cc. Sound c. Find the word that starts with Cc.": "assets/audios/sentences/frog_prompt_cc.mp3",
  "Letter Cc. Sound /c/. Find the word that starts with Cc.": "assets/audios/sentences/frog_prompt_cc.mp3",
  "Letter Cc. Find the word that starts with Cc": "assets/audios/sentences/frog_intro_cc.mp3",
  "Letter Gg. Sound g. Find the word that starts with Gg.": "assets/audios/sentences/frog_prompt_gg.mp3",
  "Letter Gg. Sound /g/. Find the word that starts with Gg.": "assets/audios/sentences/frog_prompt_gg.mp3",
  "Letter Gg. Find the word that starts with Gg": "assets/audios/sentences/frog_intro_gg.mp3",
  "Letter Pp. Sound p. Find the word that starts with Pp.": "assets/audios/sentences/frog_prompt_pp.mp3",
  "Letter Pp. Sound /p/. Find the word that starts with Pp.": "assets/audios/sentences/frog_prompt_pp.mp3",
  "Letter Pp. Find the word that starts with Pp": "assets/audios/sentences/frog_intro_pp.mp3",
  "What does the boy want to eat? The hungry boy wants a slice of warm bread.": "assets/audios/sentences/frog_act_77b2c2a2.mp3",
  "The hungry boy wants a slice of warm bread. What does the boy want to eat?": "assets/audios/sentences/frog_act_77b2c2a2.mp3",
  "Where does the cow stay? The friendly cow stays among the meadow grass.": "assets/audios/sentences/frog_act_c14bd809.mp3",
  "The friendly cow stays among the meadow grass. Where does the cow stay?": "assets/audios/sentences/frog_act_c14bd809.mp3",
  "What can the playful cat do? The playful cat can catch the little mouse.": "assets/audios/sentences/frog_act_aafec6af.mp3",
  "The playful cat can catch the little mouse. What can the playful cat do?": "assets/audios/sentences/frog_act_aafec6af.mp3",
  "What can the green frog do in the pond? The big green frog can swim and jump.": "assets/audios/sentences/frog_act_286cb9b6.mp3",
  "The big green frog can swim and jump. What can the green frog do in the pond?": "assets/audios/sentences/frog_act_286cb9b6.mp3",
  "What makes a loud beat? Listen to the loud drum beat in music class.": "assets/audios/sentences/frog_act_ecef9351.mp3",
  "Listen to the loud drum beat in music class. What makes a loud beat?": "assets/audios/sentences/frog_act_ecef9351.mp3"
};
